export const ORDER_EXPORT_COLUMNS = [
    'branch_code',
    'branch_name',
    'order_created_at',
    'received_at',
    'ready_at',
    'order_number',
    'invoice_no',
    'customer_name',
    'customer_whatsapp',
    'services',
    'qty',
    'order_status',
    'payment_status',
    'subtotal',
    'discount_type',
    'discount',
    'dp_amount',
    'grand_total',
    'paid_amount',
    'due_amount',
    'cashier',
    'notes',
] as const;

const LABELS: Record<string, string> = {
    branch_code: 'Kode Cabang',
    branch_name: 'Cabang',
    invoice: 'Invoice',
    order_number: 'No Order',
    invoice_no: 'No Invoice',
    order_created_at: 'Tanggal Order',
    received_at: 'Tanggal Masuk',
    ready_at: 'Tanggal Selesai',
    customer_name: 'Customer',
    customer_whatsapp: 'WhatsApp',
    customer_address: 'Alamat',
    services: 'Service',
    qty: 'Qty',
    order_status: 'Status Order',
    payment_status: 'Status Bayar',
    payment_method: 'Metode Bayar',
    payment_amount: 'Nominal Bayar',
    paid_at: 'Tanggal Bayar',
    payment_note: 'Catatan Bayar',
    subtotal: 'Subtotal',
    discount: 'Diskon',
    dp_amount: 'DP',
    grand_total: 'Grand Total',
    paid_amount: 'Total Dibayar',
    due_amount: 'Sisa Bayar',
    cashier: 'Kasir',
    discount_type: 'Tipe Diskon',
    notes: 'Catatan',
};

export function reportColumnLabel(column: string): string {
    return LABELS[column] ?? column;
}
